### ISSUE TITLE
User registration, management page flow sketch

### ISSUE THREAD

**Issue by mrteera** [mrteera/web16-06#27]
```
Sketch your user registration and management page flow. See the example on the course home page for an idea.
```

**Comment by ReshmaDangol** [comment]
![uml](https://cloud.githubusercontent.com/assets/6426471/19303969/f9dada0c-9094-11e6-8e13-bd72cb5a23c4.png)

**Comment by ReshmaDangol** [comment]
![uml 1](https://cloud.githubusercontent.com/assets/6426471/19311237/aca73280-90b7-11e6-96a8-a68d6955008c.png)

**Comment by ReshmaDangol** [comment]
![uml 2](https://cloud.githubusercontent.com/assets/6426471/19314376/1d004b96-90c4-11e6-905d-0b8dff0db630.png)
