### ISSUE TITLE
User registration and login pages Implementation

### ISSUE THREAD

**Issue by mrteera** [mrteera/web16-06#28]

**Comment by ReshmaDangol** [comment]
Use Cucumber for user acceptance test

**Comment by ReshmaDangol** [comment]
![screenshot from 2016-10-12 22-21-49](https://cloud.githubusercontent.com/assets/6426471/19316082/4cf330e2-90ca-11e6-90cb-693570b8b8ca.png)

**Comment by mrteera** [comment]
![screen shot 2559-10-12 at 11 58 30 pm](https://cloud.githubusercontent.com/assets/1741387/19319618/d69a26c2-90d7-11e6-8a0b-7226ecc967e5.png)

![screen shot 2559-10-13 at 12 21 38 am](https://cloud.githubusercontent.com/assets/1741387/19320341/12dccbdc-90db-11e6-9004-8cbe7fd63aa7.png)
