### ISSUE TITLE
User admin pages

### ISSUE THREAD

**Issue by mrteera** [mrteera/web16-06#29]
Again using BDD, build the user administration pages. Make sure admin can 
- [x]  see recently registered users
- [x] ban a user
- [x] see statistics on user registrations.

**Comment by mrteera** [comment]
Spike these libraries first:
https://www.ruby-toolbox.com/projects/rails_admin
https://github.com/sferik/rails_admin
http://activeadmin.info/

**Comment by ReshmaDangol** [comment]
Admin authentication added for the user statistics page
