### ISSUE TITLE
CI and Deployment

### ISSUE THREAD

**Issue by mrteera** [mrteera/web16-06#33]
```
Use your issue tracker and CI server to their full potential. Start an issue in the issue tracker before you begin any work. Get email notification of broken builds running, and get the CI server to report test coverage and code quality metrics.
```
- [x] CI
- [x] Deployment
- [x] code quality metrics
- [x] test coverage report

**Comment by mrteera** [comment]
https://github.com/railsbp/rails_best_practices
https://github.com/backus/rubocop-rspec
https://github.com/troessner/reek

^ take a look at these 3 metrics after ps4

**Comment by ReshmaDangol** [comment]
![screenshot from 2016-10-12 22-26-14](https://cloud.githubusercontent.com/assets/6426471/19320811/f4748804-90dc-11e6-806e-c65546bb5d9e.png)
![screenshot from 2016-10-12 22-26-44](https://cloud.githubusercontent.com/assets/6426471/19320810/f4729b5c-90dc-11e6-8afa-3e930fa74bb4.png)
